#!/bin/sh
lock() {
    swaylock -n -ti $(ls /home/lozerd/.config/hypr/wallpapers/*.{png,jpg} | shuf -n 1)
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        hyprctl dispatch exit 
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
