#!/bin/zsh

wallpapers_dir=$HOME/.config/hypr/wallpapers

if [ -d "$wallpapers_dir" ]; then
    monitors=$(hyprctl monitors | rg Monitor | awk '{print $2}' | xargs)

    while true; do
        chosen_wallpaper=$(ls $wallpapers_dir/*.jpg | shuf -n 1)
        hyprctl hyprpaper unload all
        hyprctl hyprpaper preload $chosen_wallpaper

        for monitor in $(echo ${monitors}); do
            hyprctl hyprpaper wallpaper "$monitor,$chosen_wallpaper";
        done
        sleep 3600
    done

fi
