#!/bin/bash

WAYBAR_CONFIG="$HOME/.config/waybar/"
CONFIG_FILES="$WAYBAR_CONFIG/config $WAYBAR_CONFIG/style.css"

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done

