general {
    hide_cursor = true
}

background {
    monitor = 
    path = /home/lozerd/dotfiles/.config/hypr/wallpapers/arch_nz.png
    blur-passes = 5
}

input-field {
    monitor = 
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false
    placeholder_text = <span foreground="gray">Enter password...</span>
    position = 0, 50
    halign = center
    valign = center
    font_family = JetBrainsMono Nerd Font
}

label {
    monitor =
    text =  Locked
    position = 0, -30
    font_size = 20
    halign = center
    valign = center
    font_family = JetBrainsMono Nerd Font
    color = rgba(ffffffcc)
}

label {
    monitor =
    text = $TIME
    position = 0, 100
    font_size = 18
    halign = center
    valign = center
    font_family = JetBrainsMono Nerd Font
    color = rgba(aaaaaacc)
}
