
#user http;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    types_hash_max_size 4096;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    # keepalive_timeout 65;

    server_names_hash_max_size 4096;
    server_names_hash_bucket_size 256;

    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    include /etc/nginx/sites-enabled/*;
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/vhosts/*/*.conf;

    server {
    	listen 80 default_server reuseport;
        listen [::]:80 default_server reuseport;

        server_name _;

        disable_symlinks if_not_owner;

        include /etc/nginx/vhosts-includes/*.conf;

        index index.html;
        root /etc/nginx/html;
   }

   # server {
   #      listen 443 ssl default_server reuseport;
   #      listen [::]:443 ssl default_server reuseport;
   #      http2 on;
   #      http3 on;

   #      server_name _;

   #      disable_symlinks if_not_owner;

   #      include /etc/nginx/vhosts-includes/*.conf;

   #      index index.html;
   #      root /etc/nginx/html;
   # }
}
